# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-09 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Dealer', 'Dealer')], max_length=1, null=True),
        ),
    ]
