# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-10 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20191110_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='width_field',
        ),
    ]
