# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-11-10 07:57
from __future__ import unicode_literals

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20191110_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=User.models.upload_location),
        ),
    ]
